[workspace]
members = [
	"common",
	"client",
	"chat-cli",
	"server",
	"server-cli",
	"voxygen",
	"world",
]

[profile.dev]
opt-level = 2
overflow-checks = false
panic="abort"
debug = false


[profile.release]
# debug = true
debug = false
panic="abort"
codegen-units = 1
lto = true
