[workspace]
members = [
	"common",
	"client",
	"chat-cli",
	"server",
	"server-cli",
	"voxygen",
	"world",
]

[profile.dev]
opt-level = 2
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
panic = 'unwind'
incremental = true
overflow-checks = false

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = true
codegen-units = 1
panic = 'unwind'
incremental = true
overflow-checks = false

[profile.version]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'
incremental = false
overflow-checks = false
